apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
  labels:
    app: myapplication
data:
  MYSQL_HOST: host.minikube.internal
  MYSQL_USER: auth_user
  MYSQL_DB: auth
  MYSQL_PORT: "3306"
